# Generated by Django 5.0.3 on 2024-04-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
