# Generated by Django 5.0.3 on 2024-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_course_rename_password_student_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
